#!/bin/zsh

# os
case "$(uname -s)" in
  Darwin) export PLATFORM=macos ;;
  Linux)  export PLATFORM=linux ;;
  *)      export PLATFORM=unknown ;;
esac

# platform
if [[ "$PLATFORM" == "macos" ]]; then
  source ~/.config/zsh/macos.sh
elif [[ "$PLATFORM" == "linux" ]]; then
  source ~/.config/zsh/linux.sh
fi

# local machine-specific configurations
if [[ -f $HOME/.local.sh ]]; then
  source $HOME/.local.sh
fi

# macro
export EDITOR='nvim'

# key binding
bindkey -e

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#808080"
# remove underline of path
ZSH_HIGHLIGHT_STYLES[path]='none'

# Completion styling
eval "$(dircolors -b)"
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no

# alias
alias ls='ls --color=auto'
alias ll='ls -alh --color=auto'
alias cl='clear'
alias vi='nvim'
alias vif='nvim $(fzf)'
alias gs='git status -s'

# History
HISTSIZE=10000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt append_history
setopt inc_append_history
setopt share_history
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# load history before prompt shows
precmd() {
  fc -R
}

# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)
export FZF_CTRL_R_OPTS="--layout=reverse"
export FZF_DEFAULT_COMMAND='find . -type f -not -path "*/.*"'

# y shell wrapper that provides the ability to change the current working directory when exiting Yazi
function y() {
   local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
   command yazi "$@" --cwd-file="$tmp"
   IFS= read -r -d '' cwd < "$tmp"
   [ "$cwd" != "$PWD" ] && [ -d "$cwd" ] && builtin cd -- "$cwd"
   rm -f -- "$tmp"
}

# starship
export STARSHIP_CONFIG=$HOME/.config/starship/starship.toml
eval "$(starship init zsh)"
